<?php $this->layout('template::layout', ['title' => $title]) ?>

<?php $this->insert('partials::header') ?>

<div class="container">
    <figure class="d-flex align-items-center justify-content-center">
        <a href="/"><img src="/assets/img/notFound.jpg" alt=""></a>
    </figure>
</div>

<?php $this->insert('partials::footer') ?>

<?php $this->start('styles') ?>
<link rel="stylesheet" href="/assets/css/custom.css" />
<?php $this->stop() ?>

<?php $this->start('scripts') ?>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="/assets/js/main.js"></script>

<?php $this->stop() ?>