<?php $this->layout('template::layout', ['title' => $title]) ?>

<?php $this->insert('partials::header') ?>

<div class="container">
  <h1><?= $this->e($title) ?> </h1>
  <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quod harum, similique dolores, quasi sed beatae quibusdam ipsum, qui a animi placeat suscipit cum. Ullam nemo ab deserunt a, quasi commodi.</p> 
</div>

<?php $this->insert('partials::footer') ?>

<?php $this->start('styles') ?>
<link rel="stylesheet" href="../assets/css/custom.css" />
<?php $this->stop() ?>

<?php $this->start('scripts') ?>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="../assets/js/scripts.js"></script>

<?php $this->stop() ?>