<?php $this->layout('template::layout', ['title' => $title]) ?>

<?php $this->insert('partials::header') ?>

<div class="container d-flex flex-column justify-content-center align-items-center">
    <h1 class="p-3"><?= $this->e($title) ?> </h1>


    <form action="/dashboard" method="post" class="w-50">
        <div class="form-floating mb-3">
            <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
            <label for="floatingInput">Email address</label>
        </div>
        <div class="form-floating mb-3">
            <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
            <label for="floatingPassword">Password</label>
        </div>
        <div class="d-grid gap-3 col-6 mx-auto">
            <button class="btn btn-primary" type="submit">Send</button>            
        </div>
    </form>


</div>

<?php $this->insert('partials::footer') ?>

<?php $this->start('styles') ?>
<link rel="stylesheet" href="../assets/css/custom.css" />
<?php $this->stop() ?>

<?php $this->start('scripts') ?>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="../assets/js/scripts.js"></script>

<?php $this->stop() ?>